"""
@project:Bearing_Fault_Diagnosis
@Author: Phantom
@Time:2023/12/17 下午3:31
@Email: 2909981736@qq.com
"""
matdata = [{'class': 0, 'faultname': '基座,健康,载荷0',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/Normal Baseline/normal_0.mat'},
           {'class': 1, 'faultname': '基座,健康,载荷1',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/Normal Baseline/normal_1.mat'},
           {'class': 2, 'faultname': '基座,健康,载荷2',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/Normal Baseline/normal_2.mat'},
           {'class': 3, 'faultname': '基座,健康,载荷3',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/Normal Baseline/normal_3.mat'},
           {'class': 4, 'faultname': '驱动端,内圈,故障等级1,载荷0',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/12k Drive End Bearing Fault Data/Inner Race/0007/IR007_0.mat'},
           {'class': 5, 'faultname': '驱动端,内圈,故障等级1,载荷1',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/12k Drive End Bearing Fault Data/Inner Race/0007/IR007_1.mat'},
           {'class': 6, 'faultname': '驱动端,内圈,故障等级1,载荷2',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/12k Drive End Bearing Fault Data/Inner Race/0007/IR007_2.mat'},
           {'class': 7, 'faultname': '驱动端,内圈,故障等级1,载荷3',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/12k Drive End Bearing Fault Data/Inner Race/0007/IR007_3.mat'},
           {'class': 8, 'faultname': '驱动端,滚珠圈,故障等级1,载荷0',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/12k Drive End Bearing Fault Data/Ball/0007/B007_0.mat'},
           {'class': 9, 'faultname': '驱动端,滚珠圈,故障等级1,载荷1',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/12k Drive End Bearing Fault Data/Ball/0007/B007_1.mat'},
           {'class': 10, 'faultname': '驱动端,滚珠圈,故障等级1,载荷2',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/12k Drive End Bearing Fault Data/Ball/0007/B007_2.mat'},
           {'class': 11, 'faultname': '驱动端,滚珠圈,故障等级1,载荷3',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/12k Drive End Bearing Fault Data/Ball/0007/B007_3.mat'},
           {'class': 12, 'faultname': '驱动端,外圈,故障等级1,位置@6,载荷0',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/12k Drive End Bearing Fault Data/Outer Race/Centered/0007/OR007@6_0.mat'},
           {'class': 13, 'faultname': '驱动端,外圈,故障等级1,位置@6,载荷1',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/12k Drive End Bearing Fault Data/Outer Race/Centered/0007/OR007@6_1.mat'},
           {'class': 14, 'faultname': '驱动端,外圈,故障等级1,位置@6,载荷2',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/12k Drive End Bearing Fault Data/Outer Race/Centered/0007/OR007@6_2.mat'},
           {'class': 15, 'faultname': '驱动端,外圈,故障等级1,位置@6,载荷3',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/12k Drive End Bearing Fault Data/Outer Race/Centered/0007/OR007@6_3.mat'},
           {'class': 16, 'faultname': '驱动端,外圈,故障等级1,位置@3,载荷0',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/12k Drive End Bearing Fault Data/Outer Race/Orthogonal/0007/144.mat'},
           {'class': 17, 'faultname': '驱动端,外圈,故障等级1,位置@3,载荷1',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/12k Drive End Bearing Fault Data/Outer Race/Orthogonal/0007/145.mat'},
           {'class': 18, 'faultname': '驱动端,外圈,故障等级1,位置@3,载荷2',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/12k Drive End Bearing Fault Data/Outer Race/Orthogonal/0007/146.mat'},
           {'class': 19, 'faultname': '驱动端,外圈,故障等级1,位置@3,载荷3',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/12k Drive End Bearing Fault Data/Outer Race/Orthogonal/0007/147.mat'},
           {'class': 20, 'faultname': '驱动端,外圈,故障等级1,位置@12,载荷0',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/12k Drive End Bearing Fault Data/Outer Race/Opposite/0007/OR007@12_0.mat'},
           {'class': 21, 'faultname': '驱动端,外圈,故障等级1,位置@12,载荷1',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/12k Drive End Bearing Fault Data/Outer Race/Opposite/0007/OR007@12_1.mat'},
           {'class': 22, 'faultname': '驱动端,外圈,故障等级1,位置@12,载荷2',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/12k Drive End Bearing Fault Data/Outer Race/Opposite/0007/OR007@12_2.mat'},
           {'class': 23, 'faultname': '驱动端,外圈,故障等级1,位置@12,载荷3',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/12k Drive End Bearing Fault Data/Outer Race/Opposite/0007/OR007@12_3.mat'},
           {'class': 24, 'faultname': '驱动端,内圈,故障等级2,载荷0',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/12k Drive End Bearing Fault Data/Inner Race/0014/IR014_0.mat'},
           {'class': 25, 'faultname': '驱动端,内圈,故障等级2,载荷1',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/12k Drive End Bearing Fault Data/Inner Race/0014/IR014_1.mat'},
           {'class': 26, 'faultname': '驱动端,内圈,故障等级2,载荷2',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/12k Drive End Bearing Fault Data/Inner Race/0014/IR014_2.mat'},
           {'class': 27, 'faultname': '驱动端,内圈,故障等级2,载荷3',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/12k Drive End Bearing Fault Data/Inner Race/0014/IR014_3.mat'},
           {'class': 28, 'faultname': '驱动端,滚珠圈,故障等级2,载荷0',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/12k Drive End Bearing Fault Data/Ball/0014/B014_0.mat'},
           {'class': 29, 'faultname': '驱动端,滚珠圈,故障等级2,载荷1',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/12k Drive End Bearing Fault Data/Ball/0014/B014_1.mat'},
           {'class': 30, 'faultname': '驱动端,滚珠圈,故障等级2,载荷2',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/12k Drive End Bearing Fault Data/Ball/0014/B014_2.mat'},
           {'class': 31, 'faultname': '驱动端,滚珠圈,故障等级2,载荷3',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/12k Drive End Bearing Fault Data/Ball/0014/B014_3.mat'},
           {'class': 32, 'faultname': '驱动端,外圈,故障等级2,位置@6,载荷0',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/12k Drive End Bearing Fault Data/Outer Race/Centered/0014/OR014@6_0.mat'},
           {'class': 33, 'faultname': '驱动端,外圈,故障等级2,位置@6,载荷1',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/12k Drive End Bearing Fault Data/Outer Race/Centered/0014/OR014@6_1.mat'},
           {'class': 34, 'faultname': '驱动端,外圈,故障等级2,位置@6,载荷2',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/12k Drive End Bearing Fault Data/Outer Race/Centered/0014/OR014@6_2.mat'},
           {'class': 35, 'faultname': '驱动端,外圈,故障等级2,位置@6,载荷3',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/12k Drive End Bearing Fault Data/Outer Race/Centered/0014/OR014@6_3.mat'},
           {'class': 36, 'faultname': '驱动端,内圈,故障等级3,载荷0',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/12k Drive End Bearing Fault Data/Inner Race/0021/IR021_0.mat'},
           {'class': 37, 'faultname': '驱动端,内圈,故障等级3,载荷1',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/12k Drive End Bearing Fault Data/Inner Race/0021/IR021_1.mat'},
           {'class': 38, 'faultname': '驱动端,内圈,故障等级3,载荷2',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/12k Drive End Bearing Fault Data/Inner Race/0021/IR021_2.mat'},
           {'class': 39, 'faultname': '驱动端,内圈,故障等级3,载荷3',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/12k Drive End Bearing Fault Data/Inner Race/0021/IR021_3.mat'},
           {'class': 40, 'faultname': '驱动端,滚珠圈,故障等级3,载荷0',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/12k Drive End Bearing Fault Data/Ball/0021/B021_0.mat'},
           {'class': 41, 'faultname': '驱动端,滚珠圈,故障等级3,载荷1',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/12k Drive End Bearing Fault Data/Ball/0021/B021_1.mat'},
           {'class': 42, 'faultname': '驱动端,滚珠圈,故障等级3,载荷2',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/12k Drive End Bearing Fault Data/Ball/0021/B021_2.mat'},
           {'class': 43, 'faultname': '驱动端,滚珠圈,故障等级3,载荷3',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/12k Drive End Bearing Fault Data/Ball/0021/B021_3.mat'},
           {'class': 44, 'faultname': '驱动端,外圈,故障等级3,位置@6,载荷0',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/12k Drive End Bearing Fault Data/Outer Race/Centered/0021/OR021@6_0.mat'},
           {'class': 45, 'faultname': '驱动端,外圈,故障等级3,位置@6,载荷1',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/12k Drive End Bearing Fault Data/Outer Race/Centered/0021/OR021@6_1.mat'},
           {'class': 46, 'faultname': '驱动端,外圈,故障等级3,位置@6,载荷2',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/12k Drive End Bearing Fault Data/Outer Race/Centered/0021/OR021@6_2.mat'},
           {'class': 47, 'faultname': '驱动端,外圈,故障等级3,位置@6,载荷3',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/12k Drive End Bearing Fault Data/Outer Race/Centered/0021/OR021@6_3.mat'},
           {'class': 48, 'faultname': '驱动端,外圈,故障等级3,位置@3,载荷0',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/12k Drive End Bearing Fault Data/Outer Race/Orthogonal/0021/246.mat'},
           {'class': 49, 'faultname': '驱动端,外圈,故障等级3,位置@3,载荷0',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/12k Drive End Bearing Fault Data/Outer Race/Orthogonal/0021/247.mat'},
           {'class': 50, 'faultname': '驱动端,外圈,故障等级3,位置@3,载荷0',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/12k Drive End Bearing Fault Data/Outer Race/Orthogonal/0021/248.mat'},
           {'class': 51, 'faultname': '驱动端,外圈,故障等级3,位置@3,载荷0',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/12k Drive End Bearing Fault Data/Outer Race/Orthogonal/0021/249.mat'},
           {'class': 52, 'faultname': '驱动端,外圈,故障等级3,位置@12,载荷0',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/12k Drive End Bearing Fault Data/Outer Race/Opposite/0021/OR021@12_0.mat'},
           {'class': 53, 'faultname': '驱动端,外圈,故障等级3,位置@12,载荷0',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/12k Drive End Bearing Fault Data/Outer Race/Opposite/0021/OR021@12_1.mat'},
           {'class': 54, 'faultname': '驱动端,外圈,故障等级3,位置@12,载荷0',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/12k Drive End Bearing Fault Data/Outer Race/Opposite/0021/OR021@12_2.mat'},
           {'class': 55, 'faultname': '驱动端,外圈,故障等级3,位置@12,载荷0',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/12k Drive End Bearing Fault Data/Outer Race/Opposite/0021/OR021@12_3.mat'},
           {'class': 56, 'faultname': '驱动端,内圈,故障等级4,载荷0',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/12k Drive End Bearing Fault Data/Inner Race/0028/IR028_0.mat'},
           {'class': 57, 'faultname': '驱动端,内圈,故障等级4,载荷1',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/12k Drive End Bearing Fault Data/Inner Race/0028/IR028_1.mat'},
           {'class': 58, 'faultname': '驱动端,内圈,故障等级4,载荷2',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/12k Drive End Bearing Fault Data/Inner Race/0028/IR028_2.mat'},
           {'class': 59, 'faultname': '驱动端,内圈,故障等级4,载荷3',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/12k Drive End Bearing Fault Data/Inner Race/0028/IR028_3.mat'},
           {'class': 60, 'faultname': '驱动端,滚珠圈,故障等级4,载荷0',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/12k Drive End Bearing Fault Data/Ball/0028/B028_0.mat'},
           {'class': 61, 'faultname': '驱动端,滚珠圈,故障等级4,载荷1',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/12k Drive End Bearing Fault Data/Ball/0028/B028_1.mat'},
           {'class': 62, 'faultname': '驱动端,滚珠圈,故障等级4,载荷2',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/12k Drive End Bearing Fault Data/Ball/0028/B028_2.mat'},
           {'class': 63, 'faultname': '驱动端,滚珠圈,故障等级4,载荷3',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/12k Drive End Bearing Fault Data/Ball/0028/B028_3.mat'},
           {'class': 64, 'faultname': '风扇端,内圈,故障等级1,载荷0',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/12k Fan End Bearing Fault Data/Inner Race/0007/IR007_0.mat'},
           {'class': 65, 'faultname': '风扇端,内圈,故障等级1,载荷1',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/12k Fan End Bearing Fault Data/Inner Race/0007/IR007_1.mat'},
           {'class': 66, 'faultname': '风扇端,内圈,故障等级1,载荷2',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/12k Fan End Bearing Fault Data/Inner Race/0007/IR007_2.mat'},
           {'class': 67, 'faultname': '风扇端,内圈,故障等级1,载荷3',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/12k Fan End Bearing Fault Data/Inner Race/0007/IR007_3.mat'},
           {'class': 68, 'faultname': '风扇端,滚珠圈,故障等级1,载荷0',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/12k Fan End Bearing Fault Data/Ball/0007/B007_0.mat'},
           {'class': 69, 'faultname': '风扇端,滚珠圈,故障等级1,载荷1',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/12k Fan End Bearing Fault Data/Ball/0007/B007_1.mat'},
           {'class': 70, 'faultname': '风扇端,滚珠圈,故障等级1,载荷2',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/12k Fan End Bearing Fault Data/Ball/0007/B007_2.mat'},
           {'class': 71, 'faultname': '风扇端,滚珠圈,故障等级1,载荷3',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/12k Fan End Bearing Fault Data/Ball/0007/B007_3.mat'},
           {'class': 72, 'faultname': '风扇端,外圈,故障等级1,位置@6,载荷0',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/12k Fan End Bearing Fault Data/Outer Race/Centered/0007/OR007@6_0.mat'},
           {'class': 73, 'faultname': '风扇端,外圈,故障等级1,位置@6,载荷1',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/12k Fan End Bearing Fault Data/Outer Race/Centered/0007/OR007@6_1.mat'},
           {'class': 74, 'faultname': '风扇端,外圈,故障等级1,位置@6,载荷2',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/12k Fan End Bearing Fault Data/Outer Race/Centered/0007/OR007@6_2.mat'},
           {'class': 75, 'faultname': '风扇端,外圈,故障等级1,位置@6,载荷3',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/12k Fan End Bearing Fault Data/Outer Race/Centered/0007/OR007@6_3.mat'},
           # 312.mat是另一个故障级别的故障数据，虽然放在这个文件夹下，但应该是官方放错文件夹了，后面会有引用
           {'class': 76, 'faultname': '风扇端,外圈,故障等级1,位置@3,载荷0',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/12k Fan End Bearing Fault Data/Outer Race/Orthogonal/0007/298.mat'},
           {'class': 77, 'faultname': '风扇端,外圈,故障等级1,位置@3,载荷1',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/12k Fan End Bearing Fault Data/Outer Race/Orthogonal/0007/299.mat'},
           {'class': 78, 'faultname': '风扇端,外圈,故障等级1,位置@3,载荷2',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/12k Fan End Bearing Fault Data/Outer Race/Orthogonal/0007/300.mat'},
           {'class': 79, 'faultname': '风扇端,外圈,故障等级1,位置@3,载荷3',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/12k Fan End Bearing Fault Data/Outer Race/Orthogonal/0007/301.mat'},
           {'class': 80, 'faultname': '风扇端,外圈,故障等级1,位置@12,载荷0',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/12k Fan End Bearing Fault Data/Outer Race/Opposite/0007/OR007@12_0.mat'},
           {'class': 81, 'faultname': '风扇端,外圈,故障等级1,位置@12,载荷1',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/12k Fan End Bearing Fault Data/Outer Race/Opposite/0007/OR007@12_1.mat'},
           {'class': 82, 'faultname': '风扇端,外圈,故障等级1,位置@12,载荷2',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/12k Fan End Bearing Fault Data/Outer Race/Opposite/0007/OR007@12_2.mat'},
           {'class': 83, 'faultname': '风扇端,外圈,故障等级1,位置@12,载荷3',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/12k Fan End Bearing Fault Data/Outer Race/Opposite/0007/OR007@12_3.mat'},
           {'class': 84, 'faultname': '风扇端,内圈,故障等级2,载荷0',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/12k Fan End Bearing Fault Data/Inner Race/0014/IR014_0.mat'},
           {'class': 85, 'faultname': '风扇端,内圈,故障等级2,载荷1',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/12k Fan End Bearing Fault Data/Inner Race/0014/IR014_1.mat'},
           {'class': 86, 'faultname': '风扇端,内圈,故障等级2,载荷2',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/12k Fan End Bearing Fault Data/Inner Race/0014/IR014_2.mat'},
           {'class': 87, 'faultname': '风扇端,内圈,故障等级2,载荷3',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/12k Fan End Bearing Fault Data/Inner Race/0014/IR014_3.mat'},
           {'class': 88, 'faultname': '风扇端,滚珠圈,故障等级2,载荷0',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/12k Fan End Bearing Fault Data/Ball/0014/B014_0.mat'},
           {'class': 89, 'faultname': '风扇端,滚珠圈,故障等级2,载荷1',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/12k Fan End Bearing Fault Data/Ball/0014/B014_1.mat'},
           {'class': 90, 'faultname': '风扇端,滚珠圈,故障等级2,载荷2',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/12k Fan End Bearing Fault Data/Ball/0014/B014_2.mat'},
           {'class': 91, 'faultname': '风扇端,滚珠圈,故障等级2,载荷3',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/12k Fan End Bearing Fault Data/Ball/0014/B014_3.mat'},
           {'class': 92, 'faultname': '风扇端,外圈,故障等级2,位置@6,载荷0',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/12k Fan End Bearing Fault Data/Outer Race/Centered/0014/OR014@6_0.mat'},
           {'class': 93, 'faultname': '风扇端,外圈,故障等级2,位置@3,载荷0',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/12k Fan End Bearing Fault Data/Outer Race/Orthogonal/0014/310.mat'},
           {'class': 94, 'faultname': '风扇端,外圈,故障等级2,位置@3,载荷1',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/12k Fan End Bearing Fault Data/Outer Race/Orthogonal/0014/311.mat'},
           {'class': 95, 'faultname': '风扇端,外圈,故障等级2,位置@3,载荷2',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/12k Fan End Bearing Fault Data/Outer Race/Orthogonal/0007/312.mat'},
           # 312顺序错误，在0007文件夹内
           {'class': 96, 'faultname': '风扇端,外圈,故障等级2,位置@3,载荷3',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/12k Fan End Bearing Fault Data/Outer Race/Orthogonal/0014/313.mat'},
           {'class': 97, 'faultname': '风扇端,内圈,故障等级3,载荷0',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/12k Fan End Bearing Fault Data/Inner Race/0021/IR021_0.mat'},
           {'class': 98, 'faultname': '风扇端,内圈,故障等级3,载荷1',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/12k Fan End Bearing Fault Data/Inner Race/0021/IR021_1.mat'},
           {'class': 99, 'faultname': '风扇端,内圈,故障等级3,载荷2',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/12k Fan End Bearing Fault Data/Inner Race/0021/IR021_2.mat'},
           {'class': 100, 'faultname': '风扇端,内圈,故障等级3,载荷3',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/12k Fan End Bearing Fault Data/Inner Race/0021/IR021_3.mat'},
           {'class': 101, 'faultname': '风扇端,滚珠圈,故障等级3,载荷0',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/12k Fan End Bearing Fault Data/Ball/0021/B021_0.mat'},
           {'class': 102, 'faultname': '风扇端,滚珠圈,故障等级3,载荷1',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/12k Fan End Bearing Fault Data/Ball/0021/B021_1.mat'},
           {'class': 103, 'faultname': '风扇端,滚珠圈,故障等级3,载荷2',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/12k Fan End Bearing Fault Data/Ball/0021/B021_2.mat'},
           {'class': 104, 'faultname': '风扇端,滚珠圈,故障等级3,载荷3',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/12k Fan End Bearing Fault Data/Ball/0021/B021_3.mat'},
           {'class': 105, 'faultname': '风扇端,外圈,故障等级3,位置@6,载荷0',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/12k Fan End Bearing Fault Data/Outer Race/Centered/0021/OR021@6_0.mat'},
           {'class': 106, 'faultname': '风扇端,外圈,故障等级3,位置@3,载荷0',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/12k Fan End Bearing Fault Data/Outer Race/Orthogonal/0021/316.mat'},
           {'class': 107, 'faultname': '风扇端,外圈,故障等级3,位置@3,载荷1',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/12k Fan End Bearing Fault Data/Outer Race/Orthogonal/0021/317.mat'},
           {'class': 108, 'faultname': '风扇端,外圈,故障等级3,位置@3,载荷2',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/12k Fan End Bearing Fault Data/Outer Race/Orthogonal/0021/318.mat'},

           # 这里的采样频率发生了变换，因此提取的特征也有所不同，视情作为另一种分类，可用于采样频率影响检测结果的验证
           {'class': 109, 'faultname': '48k驱动端,内圈,故障等级1,载荷0',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/48k Drive End Bearing Fault Data/Inner Race/0007/IR007_0.mat'},
           {'class': 110, 'faultname': '48k驱动端,内圈,故障等级1,载荷1',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/48k Drive End Bearing Fault Data/Inner Race/0007/IR007_1.mat'},
           {'class': 111, 'faultname': '48k驱动端,内圈,故障等级1,载荷2',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/48k Drive End Bearing Fault Data/Inner Race/0007/IR007_2.mat'},
           {'class': 112, 'faultname': '48k驱动端,内圈,故障等级1,载荷3',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/48k Drive End Bearing Fault Data/Inner Race/0007/IR007_3.mat'},
           {'class': 113, 'faultname': '48k驱动端,滚珠圈,故障等级1,载荷0',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/48k Drive End Bearing Fault Data/Ball/0007/B007_0.mat'},
           {'class': 114, 'faultname': '48k驱动端,滚珠圈,故障等级1,载荷1',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/48k Drive End Bearing Fault Data/Ball/0007/B007_1.mat'},
           {'class': 115, 'faultname': '48k驱动端,滚珠圈,故障等级1,载荷2',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/48k Drive End Bearing Fault Data/Ball/0007/B007_2.mat'},
           {'class': 116, 'faultname': '48k驱动端,滚珠圈,故障等级1,载荷3',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/48k Drive End Bearing Fault Data/Ball/0007/B007_3.mat'},
           {'class': 117, 'faultname': '48k驱动端,外圈,故障等级1,位置@6,载荷0',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/48k Drive End Bearing Fault Data/Outer Race/Centered/0007/OR007@6_0.mat'},
           {'class': 118, 'faultname': '48k驱动端,外圈,故障等级1,位置@6,载荷1',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/48k Drive End Bearing Fault Data/Outer Race/Centered/0007/OR007@6_1.mat'},
           {'class': 119, 'faultname': '48k驱动端,外圈,故障等级1,位置@6,载荷2',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/48k Drive End Bearing Fault Data/Outer Race/Centered/0007/OR007@6_2.mat'},
           {'class': 120, 'faultname': '48k驱动端,外圈,故障等级1,位置@6,载荷3',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/48k Drive End Bearing Fault Data/Outer Race/Centered/0007/OR007@6_3.mat'},
           {'class': 121, 'faultname': '48k驱动端,外圈,故障等级1,位置@3,载荷0',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/48k Drive End Bearing Fault Data/Outer Race/Orthogonal/0007/OR007@3_0.mat'},
           {'class': 122, 'faultname': '48k驱动端,外圈,故障等级1,位置@3,载荷1',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/48k Drive End Bearing Fault Data/Outer Race/Orthogonal/0007/OR007@3_1.mat'},
           {'class': 123, 'faultname': '48k驱动端,外圈,故障等级1,位置@3,载荷2',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/48k Drive End Bearing Fault Data/Outer Race/Orthogonal/0007/OR007@3_2.mat'},
           {'class': 124, 'faultname': '48k驱动端,外圈,故障等级1,位置@3,载荷3',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/48k Drive End Bearing Fault Data/Outer Race/Orthogonal/0007/OR007@3_3.mat'},
           {'class': 125, 'faultname': '48k驱动端,外圈,故障等级1,位置@12,载荷0',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/48k Drive End Bearing Fault Data/Outer Race/Opposite/0007/OR007@12_0.mat'},
           {'class': 126, 'faultname': '48k驱动端,外圈,故障等级1,位置@12,载荷1',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/48k Drive End Bearing Fault Data/Outer Race/Opposite/0007/OR007@12_1.mat'},
           {'class': 127, 'faultname': '48k驱动端,外圈,故障等级1,位置@12,载荷2',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/48k Drive End Bearing Fault Data/Outer Race/Opposite/0007/OR007@12_2.mat'},
           {'class': 128, 'faultname': '48k驱动端,外圈,故障等级1,位置@12,载荷3',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/48k Drive End Bearing Fault Data/Outer Race/Opposite/0007/OR007@12_3.mat'},
           {'class': 129, 'faultname': '48k驱动端,内圈,故障等级2,载荷0',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/48k Drive End Bearing Fault Data/Inner Race/0014/IR014_0.mat'},
           {'class': 130, 'faultname': '48k驱动端,内圈,故障等级2,载荷1',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/48k Drive End Bearing Fault Data/Inner Race/0014/IR014_1.mat'},
           {'class': 131, 'faultname': '48k驱动端,内圈,故障等级2,载荷2',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/48k Drive End Bearing Fault Data/Inner Race/0014/IR014_2.mat'},
           {'class': 132, 'faultname': '48k驱动端,内圈,故障等级2,载荷3',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/48k Drive End Bearing Fault Data/Inner Race/0014/IR014_3.mat'},
           {'class': 133, 'faultname': '48k驱动端,滚珠圈,故障等级2,载荷0',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/48k Drive End Bearing Fault Data/Ball/0014/B014_0.mat'},
           {'class': 134, 'faultname': '48k驱动端,滚珠圈,故障等级2,载荷1',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/48k Drive End Bearing Fault Data/Ball/0014/B014_1.mat'},
           {'class': 135, 'faultname': '48k驱动端,滚珠圈,故障等级2,载荷2',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/48k Drive End Bearing Fault Data/Ball/0014/B014_2.mat'},
           {'class': 136, 'faultname': '48k驱动端,滚珠圈,故障等级2,载荷3',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/48k Drive End Bearing Fault Data/Ball/0014/B014_3.mat'},
           {'class': 137, 'faultname': '48k驱动端,外圈,故障等级2,位置@6,载荷0',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/48k Drive End Bearing Fault Data/Outer Race/Centered/0014/OR014@6_0.mat'},
           {'class': 138, 'faultname': '48k驱动端,外圈,故障等级2,位置@6,载荷1',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/48k Drive End Bearing Fault Data/Outer Race/Centered/0014/OR014@6_1.mat'},
           {'class': 139, 'faultname': '48k驱动端,外圈,故障等级2,位置@6,载荷2',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/48k Drive End Bearing Fault Data/Outer Race/Centered/0014/OR014@6_2.mat'},
           {'class': 140, 'faultname': '48k驱动端,外圈,故障等级2,位置@6,载荷3',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/48k Drive End Bearing Fault Data/Outer Race/Centered/0014/OR014@6_3.mat'},
           {'class': 141, 'faultname': '48k驱动端,内圈,故障等级3,载荷0',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/48k Drive End Bearing Fault Data/Inner Race/0021/IR021_0.mat'},
           {'class': 142, 'faultname': '48k驱动端,内圈,故障等级3,载荷1',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/48k Drive End Bearing Fault Data/Inner Race/0021/IR021_1.mat'},
           {'class': 143, 'faultname': '48k驱动端,内圈,故障等级3,载荷2',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/48k Drive End Bearing Fault Data/Inner Race/0021/IR021_2.mat'},
           {'class': 144, 'faultname': '48k驱动端,内圈,故障等级3,载荷3',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/48k Drive End Bearing Fault Data/Inner Race/0021/IR021_3.mat'},
           {'class': 145, 'faultname': '48k驱动端,滚珠圈,故障等级3,载荷0',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/48k Drive End Bearing Fault Data/Ball/0021/B021_0.mat'},
           {'class': 146, 'faultname': '48k驱动端,滚珠圈,故障等级3,载荷1',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/48k Drive End Bearing Fault Data/Ball/0021/B021_1.mat'},
           {'class': 147, 'faultname': '48k驱动端,滚珠圈,故障等级3,载荷2',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/48k Drive End Bearing Fault Data/Ball/0021/B021_2.mat'},
           {'class': 148, 'faultname': '48k驱动端,滚珠圈,故障等级3,载荷3',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/48k Drive End Bearing Fault Data/Ball/0021/B021_3.mat'},
           {'class': 149, 'faultname': '48k驱动端,外圈,故障等级3,位置@6,载荷0',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/48k Drive End Bearing Fault Data/Outer Race/Centered/0021/OR021@6_0.mat'},
           {'class': 150, 'faultname': '48k驱动端,外圈,故障等级3,位置@6,载荷1',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/48k Drive End Bearing Fault Data/Outer Race/Centered/0021/OR021@6_1.mat'},
           {'class': 151, 'faultname': '48k驱动端,外圈,故障等级3,位置@6,载荷2',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/48k Drive End Bearing Fault Data/Outer Race/Centered/0021/OR021@6_2.mat'},
           {'class': 152, 'faultname': '48k驱动端,外圈,故障等级3,位置@6,载荷3',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/48k Drive End Bearing Fault Data/Outer Race/Centered/0021/OR021@6_3.mat'},
           {'class': 153, 'faultname': '48k驱动端,外圈,故障等级3,位置@3,载荷0',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/48k Drive End Bearing Fault Data/Outer Race/Orthogonal/0021/OR021@3_0.mat'},
           {'class': 154, 'faultname': '48k驱动端,外圈,故障等级3,位置@3,载荷1',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/48k Drive End Bearing Fault Data/Outer Race/Orthogonal/0021/OR021@3_1.mat'},
           {'class': 155, 'faultname': '48k驱动端,外圈,故障等级3,位置@3,载荷2',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/48k Drive End Bearing Fault Data/Outer Race/Orthogonal/0021/OR021@3_2.mat'},
           {'class': 156, 'faultname': '48k驱动端,外圈,故障等级3,位置@3,载荷3',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/48k Drive End Bearing Fault Data/Outer Race/Orthogonal/0021/OR021@3_3.mat'},
           {'class': 157, 'faultname': '48k驱动端,外圈,故障等级3,位置@12,载荷0',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/48k Drive End Bearing Fault Data/Outer Race/Opposite/0021/OR021@12_0.mat'},
           {'class': 158, 'faultname': '48k驱动端,外圈,故障等级3,位置@12,载荷0',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/48k Drive End Bearing Fault Data/Outer Race/Opposite/0021/OR021@12_1.mat'},
           {'class': 159, 'faultname': '48k驱动端,外圈,故障等级3,位置@12,载荷0',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/48k Drive End Bearing Fault Data/Outer Race/Opposite/0021/OR021@12_2.mat'},
           {'class': 160, 'faultname': '48k驱动端,外圈,故障等级3,位置@12,载荷0',
            'srcurl': '/mnt/E/Projects/Python/Bearing_Fault_Diagnosis/data/raw_Data/CWRU/48k Drive End Bearing Fault Data/Outer Race/Opposite/0021/OR021@12_3.mat'},
           ]
